generic:
  workspace: "./work"
  job_command: "python user.py"
  python_file: "./user.py"
  function: "main"
  main_loop_sleep_seconds: 0.01
  logging_level: INFO

job_setting:
    job_timeout_seconds: 600
    max_failure_retries: 0
    trial_id_digits: 7

resource:
  type: "mpi"
  #type: "local"
  #type: "ABCI"
  #type: "python_local"
  num_workers: 8
  mpi_npernode: 4
  mpi_bat_rt_num: 2
  mpi_bat_h_rt: "2:00:00"
  mpi_bat_file: "./qsub.sh"
  mpi_hostfile: "./hostfile"
  mpi_gpu_mode: True
  mpi_bat_make_file: True

ABCI:
  group: "[your_group_id]"
  job_script_preamble_path: ./job_script_preamble.sh
  job_execution_options: ""

optimize:
  #search_algorithm: "aiaccel.optimizer.NelderMeadOptimizer"
  search_algorithm: "aiaccel.optimizer.RandomOptimizer"
  #search_algorithm: "aiaccel.optimizer.SobolOptimizer"
  #search_algorithm: "aiaccel.optimizer.GridOptimizer"
  #search_algorithm: "aiaccel.optimizer.TpeOptimizer"
  goal: "minimize"
  trial_number: 8
  rand_seed: 42
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: 0.1
      upper: 1.9
