generic:
    workspace: ''
    job_command: ''
    python_file: ''
    function: ''
    enabled_variable_name_argumentation: True
    main_loop_sleep_seconds: 0.01
    logging_level: ERROR

resource:
    type: local
    num_workers: 1
    mpi_npernode: 4
    mpi_enviroment: "ABCI"
    mpi_bat_rt_type: "F"
    mpi_bat_rt_num: 1
    mpi_bat_h_rt: "72:00:00"
    mpi_bat_root_dir: "~/mpi_work"
    mpi_bat_venv_dir: "./mpienv"
    mpi_bat_aiaccel_dir: "./aiaccel"
    mpi_bat_config_dir: "./sphere_cpu_1node_1try"
    mpi_bat_file: "./qsub.sh"
    mpi_hostfile: "./hostfile"
    mpi_gpu_mode: True
    mpi_bat_make_file: True

ABCI:
    group: '[group]'
    job_execution_options: ''
    job_script_preamble: ''
    job_script_preamble_inline: ''

optimize:
    search_algorithm: aiaccel.optimizer.NelderMeadOptimizer
    # goal: minimize
    goal: [minimize]
    trial_number: 30
    rand_seed: 42
    sobol_scramble: True
    grid_accept_small_trial_number: False
    grid_sampling_method: 'IN_ORDER'
    parameters: []

job_setting:
    job_timeout_seconds: 600
    max_failure_retries: 0
    trial_id_digits: 7
