generic:
    workspace: ''
    job_command: ''
    python_file: ''
    function: ''
    main_loop_sleep_seconds: 0.01
    logging_level: INFO

resource:
    type: local
    num_workers: 1

ABCI:
    group: '[group]'
    job_script_preamble: ./job_script_preamble.sh
    job_execution_options: ''

optimize:
    search_algorithm: aiaccel.optimizer.NelderMeadOptimizer
    # goal: minimize
    goal: [minimize]
    trial_number: 30
    rand_seed: 42
    sobol_scramble: True
    grid_accept_small_trial_number: False
    grid_sampling_method: 'IN_ORDER'
    parameters: []

job_setting:
    job_timeout_seconds: 600
    max_failure_retries: 0
    trial_id_digits: 7
