generic:
  workspace: "./work"
  job_command: "python user.py"
  # python_file: "./user.py"
  # function: "main"
  main_loop_sleep_seconds: 0.01
  logging_level: INFO

resource:
  type: "abci"
  # type: "local"
  # type: "python_local"
  num_workers: 4

job_setting:
    job_timeout_seconds: 600
    max_failure_retries: 0
    trial_id_digits: 7

ABCI:
  group: "[group]"
  job_script_preamble: ./job_script_preamble.sh
  job_execution_options: ""

optimize:
  # search_algorithm: "aiaccel.optimizer.NelderMeadOptimizer"
  # search_algorithm: "aiaccel.optimizer.RandomOptimizer"
  search_algorithm: "aiaccel.optimizer.SobolOptimizer"
  # search_algorithm: "aiaccel.optimizer.GridOptimizer"
  # search_algorithm: "aiaccel.optimizer.TpeOptimizer"
  goal: "minimize"
  trial_number: 100
  rand_seed: 42
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: 0.0
      upper: 5.0
    -
      name: "x2"
      type: "uniform_float"
      lower: 0.0
      upper: 5.0
      initial: 1.0
